kind = "mobile"
previewPath = "/"
title = "Build A Boat"
version = "1.0.0"
id = "artifacts/boat-game"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/" ]
localPort = 22996

[services.development]
run = "pnpm --filter @workspace/boat-game run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/boat-game", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/boat-game", "run", "serve" ]

[services.env]
PORT = "22996"
BASE_PATH = "/"
